
backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Блог"
    folder: "posts"
    create: true
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Текст", name: "body", widget: "markdown" }
      - { label: "Изображение", name: "image", widget: "image", required: false }
  - name: "gallery"
    label: "Галерея"
    folder: "gallery"
    create: true
    fields:
      - { label: "Описание", name: "caption", widget: "string" }
      - { label: "Фотография", name: "image", widget: "image" }
